### ISSUE TITLE
help please :)

### ISSUE THREAD

**Issue by xxsle** [leftfield-geospatial/simple-ortho#12]
hello. what format is your dsm input data? what format was the grid, triangulation etc.?

**Comment by dugalh** [comment]
Hello.  If you have comments or questions relating to a previous issue, please comment in that issue's thread rather than opening a new issue.  

The DEM should be a GeoTIFF where pixel values are heights in the same units as the camera heights (usually meters).  There are no specific requirements for the DEM CRS or resolution.  You can specify ``dem_band`` in the [configuration file](https://github.com/leftfield-geospatial/simple-ortho#configuration-file) if the heights are not in the first band of the GeoTIFF.  See the [DEM included in the test data](https://github.com/leftfield-geospatial/simple-ortho/blob/7fb226c467557093fe6273791d031499191cd634/data/inputs/test_example/dem.tif) for an example.
